"""Add direction and specialization fields

Revision ID: 8920a4c197dc
Revises: 599eee7e4faa
Create Date: 2025-04-23 18:19:01.674532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8920a4c197dc'
down_revision = '599eee7e4faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('specialization', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('specialization')
        batch_op.drop_column('direction')

    # ### end Alembic commands ###
